version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Files stored in the repository root
    directory: '/'
    # Check for updates weekly
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Etc/UTC'
    # Include a list of updated dependencies
    commit-message:
      prefix: 'ci'
      include: 'scope'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
    # Allow up to 20 open pull requests for dependencies
    open-pull-requests-limit: 20

  # Maintain dependencies for PNPM
  - package-ecosystem: 'npm'
    # Files stored in the repository root
    directory: '/'
    # Check for updates every weekday
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Etc/UTC'
    # Include a list of updated dependencies
    commit-message:
      prefix: 'chore'
      include: 'scope'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 20
    # Allow only direct dependencies to be updated
    allow:
      - dependency-type: 'direct'
    # Ignore major version updates to avoid engine incompatibility
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    # Optional: safer versioning to prefer patch/minor bumps only
    versioning-strategy: increase
    # Create a group of dependencies to be updated together in one pull request
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
      ethers:
        patterns:
          - 'ethers'
          - '@ethersproject/*'
      lingui:
        patterns:
          - '@lingui/*'
      react-router:
        patterns:
          - 'react-router'
          - 'react-router-dom'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
