name: Artifact Upload

on:
  push:
    branches:
      - img-permutator
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCLOUD_STORAGE_SERVICE_ACCOUNT }}
          path: packages/nounsbr-img-permutator/assets/
          destination: nounsbrdao.appspot.com/src-main/assets/
          parent: false
