name: Contracts CD

on:
  release:
    types: 
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn 
      - run: yarn build
      - name: Run contract tests
        run: |
          cd packages/nouns-contracts
          yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
  build_and_deploy:
    name: Build and Deploy
    needs: build_and_test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn 
      - run: yarn build
      - name: Deploy contract to Rinkeby
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: |
          cd packages/nouns-contracts
          npx hardhat deploy-ci --network rinkeby
      - name: Verify contract on Etherscan
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          cd packages/nouns-contracts
          echo "Giving Etherscan time to index"
          sleep 60 # This could be replaced by polling etherscan on that address, wait for non-404
          npx hardhat verify --network rinkeby `cat logs/deploy.json| jq -r '.contractAddress'`
      - name: Look here for contract info
        run: |
          cd packages/nouns-contracts
          echo "Contract deployed on Rinkeby to `cat logs/deploy.json| jq -r '.contractAddress'`"
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
