name: Preview Artifact Upload

on:
  push:
    branches:
      # Match branches within the img-permutator/ path
      # Double glob (**) matches a full path so even img-permutator/foo/bar would match
      - 'img-permutator-preview/src-**'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/img-permutator-preview/})"
        id: extract_branch
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCLOUD_STORAGE_SERVICE_ACCOUNT }}
          path: packages/nouns-img-permutator/assets
          destination: nounsdao.appspot.com/${{ steps.extract_branch.outputs.branch }}
          parent: false
